services:
  laminas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 80:80
    expose:
      - 80
    volumes:
     - .:/var/www
    links:
     - db:db
  db:
    image: mysql:5.7
    ports:
     - 3306:3306
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
     - ./.data/db:/var/lib/mysql
     - ./.docker/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_USER: "webcms"
      MYSQL_PASSWORD: "webcms"
      MYSQL_DATABASE: "webcms"
      MYSQL_ROOT_PASSWORD: "root"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - 8080:80
    environment:
     PMA_HOST: db
