<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">Welcome to<br>Webinertia's MVCore!</h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/webinertia/webinertia-mvc" target="_blank">Webinertia MVC Core</a>.
        This MVC Core application is the foundation of Aurora CMS. The Webinertia team provides focused implementations
        of several Laminas components that are developed to provide us with the implementations we need to build Aurora CMS.
        Use them stand alone along side the Laminas components or install the entire webinertia-mvc package. It's up to you
        since they will work either way with a simple composer require or clone and composer install.
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/webinertia" target="_blank">
        Check Webinertia on GitHub &raquo;
    </a>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Follow Development</h2>
            <div class="card-body">
                <p>
                    All of Webinertia's opensource packages are under active development. If you are
                    interested in following the development, you can check
                    <a href="https://getlaminas.org/blog/">Laminas dev blog</a>,
                    and <a href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:webinertia" target="_blank">Webinertia issue tracker</a>
                    (link requires a GitHub account). This is a great resource
                    for staying up to date with the latest developments!
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="https://github.com/webinertia" target="_blank">Webinertia Github &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Discover Modules</h2>
            <div class="card-body">
                <p>
                    Webinertia MVC is a modular application.
                    You can find multiple compatible modules on packagist. Aurora supports
                    any module ddeveloped by Webinertia or Laminas MVC.
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="https://packagist.org/?tags=webinertia" target="_blank">
                    Explore Webinertia Modules &raquo;</a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card h-100">
            <h2 class="card-header">Help &amp; Support</h2>
            <div class="card-body">
                <p>
                    If you need any help or support while developing with any Webinertia component or
                    Aurora CMS please see the related Wiki for that component on Github or related
                    repo's discussion tab. Every component will have both!
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" href="https://github.com/webinertia/community/discussions" target="_blank">Community discussions &raquo;</a>
            </div>
        </div>
    </div>
</div>
