name: docker-build

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Build and run docker compose file
        run: |
          docker-compose up -d --build
          docker-compose run laminas echo "ok"

